### ISSUE TITLE
Not working a function _codeception_get_command_list without `--no-ansi`

### ISSUE THREAD

**Issue by sorbing** [shengyou/codeception-zsh-plugin#1]
I have not worked it's plugin until I added the parameter `--no-ansi` in function `_codeception_get_command_list`:
Before:

```
_codeception_get_command_list () {
  vendor/bin/codecept \
  ...
```

After:

```
_codeception_get_command_list () {
  vendor/bin/codecept --no-ansi \
```

Not work correctly `awk`.. Perhaps this is due to the environment.
My OS: `Linux Ubuntu 13.04 x64 3.8.0-35-generic`

**Comment by shengyou** [comment]
Hi, this pull request had fix this problem. You could try it: https://github.com/shengyou/codeception-zsh-plugin/commit/0719a8b8d66414aa81522d9d17d9699229755ee8
