### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by babab** [shengyou/codeception-zsh-plugin#2]
Hi Shengyou,

I am thinking about expanding on your completion file with missing commands and flags, and possibly make a version for system-wide install and add support for phar/non-composer installs. But since there is no license information, I am not sure at what terms I can do if I decide to proceed with this.

Regards,

Benjamin

**Comment by shengyou** [comment]
Hi Benjamin,

Thanks for interesting on my plugin, I'm glad that you can help me to improve this project. I just add the MIT license in project repo. Thanks for notice me about this. If I miss something, feel free to contact me!

Regards, 

Shengyou

**Comment by babab** [comment]
Thanks. After looking more closely I don't think any command or flags are missing, but I hope to be able to submit a PR later this week for _optionally_ installing the completion file into `/usr/share/zsh/site-functions`.
